//09/11/2008.
//file: photo.h, generated by computer.
#ifndef _09_11_2008_
#define _09_11_2008_

//button.
#define ID_BTN_SLIDESHOW 0
#define ID_BTN_MODE 1
#define ID_BTN_EFFECT 2
#define ID_BTN_TIME 3

//check button.

//radio button.

//label.
#define ID_LBL_PHOTO 0

//list box.
#define ID_LBX_PLAYMODE 0
#define ID_LBX_EFFECTS 1
#define ID_LBX_INTERVAL 2

//progress bar.
#define ID_PIC_Y1 0
#define ID_PIC_Y2 1
#define ID_PIC_Y3 2
#define ID_PIC_Y4 3
#define ID_PIC_M1 4
#define ID_PIC_M2 5
#define ID_PIC_H2 6
#define ID_PIC_H1 7
#define ID_PIC_MN1 8
#define ID_PIC_MN2 9
#define ID_PIC_PP 10
#define ID_PIC_CALENDAR 11


//window.
#define ID_WND_PHOTO 0
#define ID_WND_MODE 1
#define ID_WND_EFFECTS 2
#define ID_WND_TIME 3
#define ID_WND_SLIDEMAIN 4
#define ID_WND_CALENDAR 5
#define ID_WND_SLIDESHOW 6

#endif //_09_11_2008_
