//10/23/2008.
//file: Setting.h, generated by computer.
#ifndef _10_23_2008_
#define _10_23_2008_

//button.
#define ID_BTN_LANGUAGE 0
#define ID_BTN_BRIGHT 1
#define ID_BTN_SUBJECT 2
#define ID_BTN_AUTO 3
#define ID_BTN_STATUS 4
#define ID_BTN_RESET 5
#define ID_BTN_CONTRAST 6
#define ID_BTN_BRIGHTNESS 7
#define ID_BTN_AUTO_ON 8
#define ID_BTN_AUTO_OFF 9
#define ID_BTN_HH 10
#define ID_BTN_MM 11
#define ID_BTN_CONFLAG 12

//check button.

//radio button.

//label.
#define ID_LBL_TITLE_2 0
#define ID_LBL_BRIGVALUE 1
#define ID_LBL_BR0 2
#define ID_LBL_BR100 3
#define ID_LBL_AUTO_1 4
#define ID_LBL_AUTO_2 5
#define ID_LBL_FMVISION 6
#define ID_LBL_FREEMEM 7
#define ID_LBL_ST_SV 8
#define ID_LBL_ST_FM 9
#define ID_LBL_REST_MES 10
#define ID_LBL_MES 11
#define ID_LBL_SETTIME 12
#define ID_LBL_TIME_TS 13
#define ID_LBL_TITLE_1 14
#define ID_LBL_CONTVALUE 15
#define ID_LBL_CON0 16
#define ID_LBL_CON100 17

//list box.
#define ID_LBX_LGU 0
#define ID_LBX_SUBJECT 1

//progress bar.
#define ID_PGB_BRIGHT 0
#define ID_PGB_CONT 1

//window.
#define ID_WND_SETTING 0
#define ID_WND_LANGUAGE 1
#define ID_WND_BRIGHT 2
#define ID_WND_SUBJECT 3
#define ID_WND_AUTO 4
#define ID_WND_STATUS 5
#define ID_WND_RESET 6
#define ID_WND_MESSAGE 7
#define ID_WND_SETTIME 8
#define ID_WND_SETTING_BK 9
#define ID_WND_CONT 10

#endif //_10_23_2008_
