//03/24/2008.
//file: rc.h, generated by computer.
#ifndef _03_24_2008_
#define _03_24_2008_

//button.
#define ID_BTN_TIME 0
#define ID_BTN_ALARM 1
#define ID_BTN_CLOCK 2
#define ID_BTN_CALENDAR 3
#define ID_BTN_HOUR 4
#define ID_BTN_MINUTE 5
#define ID_BTN_YEAR 6
#define ID_BTN_MONTH 7
#define ID_BTN_DAY 8
#define ID_BTN_ALARMTIME1 9
#define ID_BTN_ALARMTIME2 10
#define ID_BTN_ALARMON 11
#define ID_BTN_ALARMBRO 12
#define ID_BTN_CLOCKON 13
#define ID_BTN_CLOCKLOCA 14

//check button.

//radio button.

//label.
#define ID_LBL5 0
#define ID_LBL4 1
#define ID_LBL1 2
#define ID_LBL2 3
#define ID_LBL3 4
#define ID_LBL6 5
#define ID_LBL9 6
#define ID_LBL8 7
#define ID_LBL7 8
#define ID_LBL10 9
#define ID_LBL11 10
#define ID_LBL12 11
#define ID_LBL13 12
#define ID_LBL14 13
#define ID_LBL145 14
#define ID_LBL16 15
#define ID_LBL17 16
#define ID_LBL18 17
#define ID_LBL19 18
#define ID_LBL20 19
#define ID_LBL21 20
#define ID_LBL22 21
#define ID_LBL23 22
#define ID_LBL24 23
#define ID_LBL25 24
#define ID_LBL26 25
#define ID_LBL27 26
#define ID_LBL28 27
#define ID_LBL29 28
#define ID_LBL30 29
#define ID_LBL31 30
#define ID_LBL32 31
#define ID_LBL33 32
#define ID_LBL34 33
#define ID_LBL35 34
#define ID_LBL36 35
#define ID_LBL37 36
#define ID_LBL38 37
#define ID_LBL39 38
#define ID_LBL40 39
#define ID_LBL41 40
#define ID_LBL42 41
#define ID_LBL43 42
#define ID_LBL44 43
#define ID_LBL45 44
#define ID_LBL46 45
#define ID_LBL47 46
#define ID_LBL48 47
#define ID_LBL49 48
#define ID_LBL50 49
#define ID_LBL51 50
#define ID_LBL52 51
#define ID_LBL53 52
#define ID_LBL54 53
#define ID_LBL55 54
#define ID_LBL56 55
#define ID_LBL57 56

//list box.

//progress bar.
#define ID_PIC_YEAR1 0
#define ID_PIC_YEAR2 1
#define ID_PIC_YEAR3 2
#define ID_PIC_YEAR4 3
#define ID_PIC_MONTH1 4
#define ID_PIC_MONTH2 5
#define ID_PIC_GANG1 6
#define ID_PIC_GANG2 7
#define ID_PIC_DAY1 8
#define ID_PIC_DAY2 9
#define ID_PIC_HOUR1 10
#define ID_PIC_HOUR2 11
#define ID_PIC_MINUTE1 12
#define ID_PIC_MINUTE2 13
#define ID_PIC_DOT1 14
#define ID_PIC_SEC1 15
#define ID_PIC_SEC2 16

//window.
#define ID_WCLOCK 0
#define ID_WSETTIME 1
#define ID_WSETALARM 2
#define ID_WSETCLOCK 3
#define ID_WCALENDAR 4

#endif //_03_24_2008_
