//08/21/2008.
//file: clock.h, generated by computer.
#ifndef _08_21_2008_
#define _08_21_2008_

//button.
#define ID_BTN_TIME 0
#define ID_BTN_ALARM 1
#define ID_BTN_CLOCK 2
#define ID_BTN_CALENDAR 3
#define ID_BTN_YEAR 4
#define ID_BTN_MONTH 5
#define ID_BTN_DAY 6
#define ID_BTN_HOUR 7
#define ID_BTN_MINUTE 8
#define ID_BTN_WORLDTIME 9
#define ID_BTN_ALARMON 10
#define ID_BTN_ALARMTIME1 11
#define ID_BTN_ALARMTIME2 12
#define ID_BTN_ALARMBRO 13
#define ID_BTN_CLOCKON 14
#define ID_BTN_CLOCKLOCA 15
#define ID_BTN_GRYEAR 16
#define ID_BTN_GRMONTH 17
#define ID_BTN_GRDAY 18

//check button.
#define ID_CKB_CA0 0
#define ID_CKB_CA1 1
#define ID_CKB_CA2 2
#define ID_CKB_CA3 3
#define ID_CKB_CA4 4
#define ID_CKB_CA5 5
#define ID_CKB_CA6 6
#define ID_CKB_CA7 7
#define ID_CKB_CA8 8
#define ID_CKB_CA9 9
#define ID_CKB_CA10 10
#define ID_CKB_CA11 11
#define ID_CKB_CA12 12
#define ID_CKB_CA13 13
#define ID_CKB_CA14 14
#define ID_CKB_CA15 15
#define ID_CKB_CA16 16
#define ID_CKB_CA17 17
#define ID_CKB_CA18 18
#define ID_CKB_CA19 19
#define ID_CKB_CA20 20
#define ID_CKB_CA21 21
#define ID_CKB_CA22 22
#define ID_CKB_CA23 23
#define ID_CKB_CA24 24
#define ID_CKB_CA25 25
#define ID_CKB_CA26 26
#define ID_CKB_CA27 27
#define ID_CKB_CA28 28
#define ID_CKB_CA29 29
#define ID_CKB_CA30 30
#define ID_CKB_CA31 31
#define ID_CKB_CA32 32
#define ID_CKB_CA33 33
#define ID_CKB_CA34 34

//radio button.

//label.
#define ID_LBL_CLOCK 0
#define ID_LBL_TIME0 1
#define ID_LBL_TIME1 2
#define ID_LBL_TIME2 3
#define ID_LBL_TIME3 4
#define ID_LBL_TIME4 5
#define ID_LBL_TIME5 6
#define ID_LBL_ALARM0 7
#define ID_LBL_ALARM1 8
#define ID_LBL_ALARM2 9
#define ID_LBL_ALARM3 10
#define ID_LBL_CLOCK0 11
#define ID_LBL_CLOCK1 12
#define ID_LBL_CA0 13
#define ID_LBL_CA1 14
#define ID_LBL_CA2 15
#define ID_LBL_CA3 16
#define ID_LBL_CA4 17
#define ID_LBL_CA5 18
#define ID_LBL_CA6 19
#define ID_LBL_CA7 20
#define ID_LBL_LOCALAREA 21
#define ID_LBL_LOCALTIME 22
#define ID_LBL_WORLDAREA 23
#define ID_LBL_WORLDTIME 24

//list box.

//progress bar.
#define ID_PIC_GANG1 0
#define ID_PIC_GANG2 1
#define ID_PIC_HOUR1 2
#define ID_PIC_HOUR2 3
#define ID_PIC_MINUTE1 4
#define ID_PIC_MINUTE2 5
#define ID_PIC_DOT1 6
#define ID_PIC_SEC1 7
#define ID_PIC_SEC2 8
#define ID_PIC_YEAR1 9
#define ID_PIC_YEAR2 10
#define ID_PIC_YEAR3 11
#define ID_PIC_YEAR4 12
#define ID_PIC_MONTH1 13
#define ID_PIC_MONTH2 14
#define ID_PIC_DAY1 15
#define ID_PIC_DAY2 16
#define ID_PIC_WORLDMAP 17

//window.
#define ID_WCLOCK 0
#define ID_WND_TIME 1
#define ID_WND_ALARM 2
#define ID_WND_CLOCK 3
#define ID_WND_CALENDAR 4
#define ID_WND_WORLDTIME 5

#endif //_08_21_2008_
