//09/02/2008.
//file: desktop.h, generated by computer.
#ifndef _09_02_2008_
#define _09_02_2008_

//button.
#define ID_BTN_AUDIO 0
#define ID_BTN_PHOTO 1
#define ID_BTN_FILE 2
#define ID_BTN_CLOCK 3
#define ID_BTN_SETTING 4
#define ID_BTN_READER 5

//check button.

//radio button.

//label.
#define ID_LBL_DESKTOP 0
#define ID_LBL_DATE 1
#define ID_LBL_TIME 2
#define ID_LBL_DISKHINT 3
#define ID_LBL_ALARMHINT 4

//list box.

//progress bar.

//window.
#define ID_WND_DESKTOP 0
#define ID_WND_DISKHINT 1
#define ID_WND_ALARMHINT 2

//button group
#define ID_BTNGRP_TYPE0 0
#define ID_BTNGRP_TYPE1 1

#endif //_09_02_2008_
