//11/25/2008.
//file: fbrowse.h, generated by computer.
#ifndef _11_25_2008_
#define _11_25_2008_

//button.
#define ID_BTN_FILEOPEN 0
#define ID_BTN_FILECOPY 1
#define ID_BTN_FILEDELETE 2
#define ID_BTN_FILEATTRIBUTE 3
#define ID_BTN_OP_YES 4
#define ID_BTN_OP_NO 5
#define ID_BTN_MUSIC 6
#define ID_BTN_PICTURE 7
#define ID_BTN_BOOK 8
#define ID_BTN_OK 9

//check button.

//radio button.

//label.
#define ID_LBL_YES_NO 0
#define ID_LBL_FILE_SIZE 1
#define ID_LBL_FILE_SIZE1 2
#define ID_LBL_FILE_TYPE 3
#define ID_LBL_FILE_TYPE1 4
#define ID_LBL_DIRPATH 5
#define ID_LBL_FILEINFO 6

//list box.
#define ID_LBX_FILE 0

//progress bar.
#define ID_PIC_DEMO 0

//window.
#define ID_WND_FBROWSER 0
#define ID_WND_FILEOP 1
#define ID_WND_YESNO 2
#define ID_WND_FILE_ATTRIBUTE 3
#define ID_WND_MARK 4
#define ID_WND_PICVIEWER 5

#endif //_11_25_2008_
