//05/12/2008.
//file: resource.h, generated by computer.
#ifndef _05_12_2008_
#define _05_12_2008_

//button.
#define IDB_PRE 0
#define IDB_STOP 1
#define IDB_FB 2
#define IDB_MODE 3
#define IDB_PL 4
#define IDB_VOL 5
#define IDB_NEXT 6
#define IDB_PI_PLAY 7
#define IDB_PI_DEL 8
#define IDB_PI_UP 9
#define IDB_PI_DOWN 10
#define IDB_PI_ALL_DEL 11
#define IDB_FBI_PLAY 12
#define IDB_FBI_ADD 13

//check button.
#define IDCB_PP 0

//radio button.

//label.
#define IDL_SONG 0
#define IDL_SINGER 1
#define IDL_ALBUM 2
#define IDL_TIME 3
#define IDL_SONG_ORDER 4
#define IDL_CUR_POS 5
#define IDL_TIME_DISP 6
#define IDL_FAV 7
#define IDL_FOLDER 8

//list box.
#define IDPL_BOX 0
#define IDFB_BOX 1

//progress bar.
#define IDPB_TIME 0
#define IDPB_VOL 1

//window.
#define IDW_WINDOW 0
#define IDW_PLW 1
#define IDW_PIW 2
#define IDW_FBIW 3
#define IDW_FBW 4

#endif //_05_12_2008_
