//04/23/2008.
//file: reader.h, generated by computer.
#ifndef _04_23_2008_
#define _04_23_2008_

//button.
#define ID_BTN_MYBOOK 0
#define ID_BTN_RF 1
#define ID_BTN_MYBM 2
#define ID_BTN_ADDBM 3
#define ID_BTN_AUTO 4

//check button.

//radio button.

//label.
#define ID_LBL_FILENAME 0
#define ID_LBL_TIME_BK 1
#define ID_LBL_SCALE 2
#define ID_LBL_MENU 3
#define ID_LBL_TIME_MU 4
#define ID_LBL_TR 5

//list box.
#define ID_LBX_RECENT 0
#define ID_LBX_MYBOOK 1
#define ID_LBX_MYBM 2

//progress bar.

//window.
#define ID_WND_CONTEXT_BK 0
#define ID_WND_TRBK 1
#define ID_WND_RECENT 2
#define ID_WND_MYBOOK 3
#define ID_WND_MYBM 4
#define ID_WND_CONTEXT 5
#define ID_WND_TRMENU 6

#endif //_04_23_2008_
